### ISSUE TITLE
Input : in time.

### ISSUE THREAD

**Issue by qwelyt** [Mousaka/elm-clock-countdown#2]
Can't input `40:00`, you have to input `4000`.
This is quite confusing as the placeholder says `10:00`. So the input format does not reflect the format that is shown.

Have you considered using some sort of ui-mask?

**Comment by Mousaka** [comment]
have considered it but have not put any time into it yet. Will try fix after work hours :]

**Comment by Mousaka** [comment]
Solved! => https://github.com/Mousaka/elm-clock-countdown/commit/50da414d7e937c2f6372428467ddfd5530018b8e?diff=unified#diff-7bf0bff306d437bb36dc5e2ace126258R14
You can now input `40:00`. There is no mask implemented yet though.
